# Generated by Django 3.2.3 on 2024-12-05 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссёр фильма')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание фильма')),
                ('release_date', models.DateField(verbose_name='Дата выпуска фильма')),
                ('image', models.ImageField(blank=True, null=True, upload_to='films/', verbose_name='Постер фильма')),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
    ]
