# Generated by Django 3.2.3 on 2024-12-06 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0004_favorite_favorite_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста'),
        ),
    ]
