# Generated by Django 3.2.3 on 2024-12-06 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0005_alter_film_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='favorited',
            field=models.ManyToManyField(related_name='film', through='films.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста'),
        ),
    ]
